Here we are going to add MRI column with paths to MRI files to the dataset.csv file. Merge will use only submitter_id column. This column will be checked to through out test group during pre-training of MRI encoder.

In [23]:
# import needed libraries
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold, StratifiedKFold
pd.set_option('display.max_columns', None)

base_path = '/mnt/public-datasets/drim/BraTS_2023'
dataset_file_path = '../src/data/dataset_balanced.csv'

In [14]:
dataframe = pd.read_csv(dataset_file_path)
dataframe.shape

(1103, 39)

In [15]:
dataframe.columns

Index(['submitter_id', 'tumor_stage', 'age_at_diagnosis', 'prior_treatment',
       'prior_malignancy', 'synchronous_malignancy', 'days_to_last_follow_up',
       'gender', 'race', 'vital_status', 'days_to_death',
       'treatments_pharmaceutical_treatment_or_therapy',
       'treatments_radiation_treatment_or_therapy', 'project_id', 'time',
       'event', 'IDH', 'MGMT', 'X1p19q', '19.20.gain', '7g10l', 'TERT', 'ATRX',
       'RNA', 'MRI', 'DNAm', 'treatments_binary',
       'treatments_radiation_binary', 'WSI_initial', 'WSI',
       'age_at_diagnosis_in_years',
       'treatments_radiation_treatment_or_therapy-f1',
       'treatments_radiation_treatment_or_therapy-f2',
       'treatments_radiation_treatment_or_therapy-f3',
       'treatments_pharmaceutical_treatment_or_therapy_f1',
       'treatments_pharmaceutical_treatment_or_therapy_f2',
       'treatments_pharmaceutical_treatment_or_therapy_f3', 'splits', 'group'],
      dtype='object')

In [16]:
dataframe.sample(5)

,submitter_id,tumor_stage,age_at_diagnosis,prior_treatment,prior_malignancy,synchronous_malignancy,days_to_last_follow_up,gender,race,vital_status,days_to_death,treatments_pharmaceutical_treatment_or_therapy,treatments_radiation_treatment_or_therapy,project_id,time,event,IDH,MGMT,X1p19q,19.20.gain,7g10l,TERT,ATRX,RNA,MRI,DNAm,treatments_binary,treatments_radiation_binary,WSI_initial,WSI,age_at_diagnosis_in_years,treatments_radiation_treatment_or_therapy-f1,treatments_radiation_treatment_or_therapy-f2,treatments_radiation_treatment_or_therapy-f3,treatments_pharmaceutical_treatment_or_therapy_f1,treatments_pharmaceutical_treatment_or_therapy_f2,treatments_pharmaceutical_treatment_or_therapy_f3,splits,group
69,TCGA-DU-6395,NaN,11584.0,No,no,No,NaN,male,white,Dead,1491.0,no,yes,LGG,4.084932,1,Mutant,Methylated,non-codel,No chr 19/20 gain,No combined CNA,Not expressed,Mutant,/DRIM/data/TCGA/GBMLGG/RNA/af44aa49-f28e-4a03-...,NaN,/DRIM/data/TCGA/GBMLGG/DNAm/f6c71436-dfd6-498d...,0,1,/mnt/public-datasets/drim/wsi/290e1fb2-9ae5-49...,/workspace/mtcp/outputs/embeddings_wsi/TCGA-DU...,31.736986,0.0,1.0,0.0,1.0,0.0,0.0,4.0,train
71,TCGA-DU-6397,NaN,16695.0,No,no,No,NaN,male,white,Dead,1401.0,no,yes,LGG,3.838356,1,Mutant,Methylated,codel,No chr 19/20 gain,No combined CNA,Expressed,WT,/DRIM/data/TCGA/GBMLGG/RNA/032b52ae-de5f-4f4c-...,NaN,/DRIM/data/TCGA/GBMLGG/DNAm/d94632dd-7d8e-4e49...,0,1,/mnt/public-datasets/drim/wsi/acedae65-0e11-41...,/workspace/mtcp/outputs/embeddings_wsi/TCGA-DU...,45.739726,0.0,1.0,0.0,1.0,0.0,0.0,5.0,test
613,TCGA-08-0353,NaN,21332.0,No,NaN,NaN,NaN,male,white,Dead,256.0,yes,yes,GBM,0.701370,1,WT,NaN,non-codel,No chr 19/20 gain,Gain chr 7 & loss chr 10,NaN,NaN,NaN,NaN,NaN,1,1,/mnt/public-datasets/drim/TCGA-GBM_WSI/c3b5755...,/workspace/mtcp/outputs/embeddings_wsi/TCGA-08...,58.443836,0.0,1.0,0.0,0.0,1.0,0.0,0.0,train
267,TCGA-HW-7486,NaN,13546.0,No,no,No,1721.0,male,white,Alive,NaN,yes,no,LGG,4.715068,0,Mutant,Methylated,codel,No chr 19/20 gain,No combined CNA,Expressed,WT,/DRIM/data/TCGA/GBMLGG/RNA/a592fdde-b880-4901-...,NaN,/DRIM/data/TCGA/GBMLGG/DNAm/7b7ece28-bac9-4641...,1,0,/mnt/public-datasets/drim/wsi/9398620d-be43-4d...,/workspace/mtcp/outputs/embeddings_wsi/TCGA-HW...,37.112329,1.0,0.0,0.0,0.0,1.0,0.0,0.0,train
721,TCGA-14-1825,NaN,25684.0,No,NaN,NaN,NaN,male,white,Dead,232.0,yes,yes,GBM,0.635616,1,WT,Unmethylated,non-codel,No chr 19/20 gain,Gain chr 7 & loss chr 10,Expressed,WT,/DRIM/data/TCGA/GBMLGG/RNA/a9671acb-4933-4825-...,/data/BraTS_2023/MRI/BraTS-GLI-00116-000,/DRIM/data/TCGA/GBMLGG/DNAm/b41c18e2-67c2-47f5...,1,1,/mnt/public-datasets/drim/TCGA-GBM_WSI/a661826...,/workspace/mtcp/outputs/embeddings_wsi/TCGA-14...,70.367123,0.0,1.0,0.0,0.0,1.0,0.0,0.0,train

In [17]:
# take only samples with brain as primary site
dataframe = dataframe[dataframe.project_id.isin(['GBM', 'LGG'])]
dataframe.shape

(1103, 39)

In [18]:
dataframe['group'].value_counts()

group
train    920
test     183
Name: count, dtype: int64

In [19]:
dataframe['splits'].value_counts()

splits
0.0    184
4.0    184
2.0    184
3.0    184
1.0    184
5.0    183
Name: count, dtype: int64

## MRI
For this part, we are using the overlap with patients from the BraTS and TCGA competitions, using the mapping file available on the competition website. Since the BraTS competition contains over a thousand cases and only 165 from the TCGA, we will first of all pre-train the models.

In [20]:
mapping_file = '../src/data/BraTS2023_2017_GLI_Mapping.xlsx'
mapping_mri = pd.read_excel(mapping_file)
print(mapping_mri.shape)
mapping_mri.sample(2)

(1255, 9)

,BraTS2023,BraTS2021,BraTS2020,BraTS2019,BraTS2018,BraTS2017,Cohort Name (if publicly available),Site No (represents the originating institution),Local ID
946,BraTS-GLI-01362-000,BraTS2021_01362,NaN,NaN,NaN,NaN,Private Collection,1,NaN
632,BraTS-GLI-01048-000,BraTS2021_01048,NaN,NaN,NaN,NaN,Private Collection,1,NaN

### pre-train

In [21]:
dataframe[~dataframe['MRI'].isna()]['splits'].value_counts()

splits
2.0    32
0.0    28
4.0    27
3.0    26
5.0    26
1.0    26
Name: count, dtype: int64

In [24]:
pretrain_mri = pd.merge(
    how='left',
    left=mapping_mri,
    right=dataframe[['submitter_id', 'group', 'splits']],
    left_on='Local ID ',
    right_on='submitter_id'
)
pretrain_mri.dropna(subset=['BraTS2023'], inplace=True)
print(f"Total patients: {len(pretrain_mri)}")

pretrain_mri['MRI'] = pretrain_mri['BraTS2023'].apply(lambda x: os.path.join(base_path, 'MRI', x))
pretrain_mri.fillna(value={'group': 'train'}, inplace=True)

def check_modalities(patients, modalities, home_dir='/data/BraTS_2023'):
    '''
    get patients only with target modalities
    '''
    patients_with_needed_modalities = []
    needed_modalities = set(modalities)
    needed_modalities.add("seg") #segmentation mask used to compute center of tumor
    for patient in patients:
        patient = os.path.join(home_dir, os.path.basename(patient))
        available_modalities = set([x.split("-")[-1].split(".")[0] for x in os.listdir(patient)])
        if needed_modalities.intersection(available_modalities) == needed_modalities:
            patients_with_needed_modalities.append(patient)
    print(f"Patients with all needed modalities: {len(patients_with_needed_modalities)}")
    return patients_with_needed_modalities

modalities = ['t1c', 't1n', 't2w', 't2f']
patients_with_needed_modalities = check_modalities(pretrain_mri['MRI'].values, modalities, home_dir=base_path + "/MRI/")
pretrain_mri = pretrain_mri[pretrain_mri['MRI'].isin(patients_with_needed_modalities)]

#validation splits
pretrain_mri_train = pretrain_mri[pretrain_mri['group'] == 'train']
pretrain_mri_test = pretrain_mri[pretrain_mri['group'] == 'test']

pretrain_mri_train_with_splits = pretrain_mri_train[pretrain_mri_train['splits'].notna()]
pretrain_mri_train_without_splits = pretrain_mri_train[pretrain_mri_train['splits'].isna()]

#proportional splits generation
ready_splits_distribution = pretrain_mri_train_with_splits['splits'].value_counts()
N = len(pretrain_mri_train) #total
k = len(ready_splits_distribution) #number of classes
additional_splits_distribution = ready_splits_distribution.apply(lambda x: (N//k - x)).sort_values()
additional_splits_distribution.iloc[:N%k] += 1
splits = []
for idxs in [[k] * v for k, v in additional_splits_distribution.items()]:
    splits.extend(idxs)
rng = np.random.default_rng()
rng.shuffle(splits) #inplace

# pretrain_mri_train_without_splits.drop('splits', axis="columns", inplace=True)
pretrain_mri_train_without_splits['splits'] = splits
pretrain_mri_test['splits'] = -1
pretrain_mri = pd.concat([pretrain_mri_train_without_splits, pretrain_mri_train_with_splits, pretrain_mri_test])

print(pretrain_mri['group'].value_counts())
print("ready splits", pretrain_mri_train_with_splits['splits'].value_counts().sort_index())
print("generated splits", pretrain_mri_train_without_splits['splits'].value_counts().sort_index())
print("total splits", pretrain_mri['splits'].value_counts().sort_index())

pretrain_mri = pretrain_mri[['submitter_id', 'group', 'splits', 'MRI']]
display(pretrain_mri.head(5))

pretrain_mri.to_csv(f'../src/data/pretrain_mri_{"_".join(modalities)}_balanced.csv', index=False)

Total patients: 1251
Patients with all needed modalities: 1251
group
train    1225
test       26
Name: count, dtype: int64
ready splits splits
0.0    28
1.0    26
2.0    32
3.0    26
4.0    27
Name: count, dtype: int64
generated splits splits
0.0    217
1.0    219
2.0    213
3.0    219
4.0    218
Name: count, dtype: int64
total splits splits
-1.0     26
 0.0    245
 1.0    245
 2.0    245
 3.0    245
 4.0    245
Name: count, dtype: int64

/tmp/ipykernel_1282277/2366581999.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pretrain_mri_train_without_splits['splits'] = splits
/tmp/ipykernel_1282277/2366581999.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pretrain_mri_test['splits'] = -1

,submitter_id,group,splits,MRI
0,NaN,train,4.0,/mnt/public-datasets/drim/BraTS_2023/MRI/BraTS...
1,NaN,train,3.0,/mnt/public-datasets/drim/BraTS_2023/MRI/BraTS...
2,NaN,train,3.0,/mnt/public-datasets/drim/BraTS_2023/MRI/BraTS...
3,NaN,train,2.0,/mnt/public-datasets/drim/BraTS_2023/MRI/BraTS...
4,NaN,train,1.0,/mnt/public-datasets/drim/BraTS_2023/MRI/BraTS...

### survival prediction task

In [27]:
mapping_mri = mapping_mri[mapping_mri['Cohort Name (if publicly available)'].str.contains('TCGA')]
print(mapping_mri.shape)
mapping_mri.sample(2)

(167, 9)

,BraTS2023,BraTS2021,BraTS2020,BraTS2019,BraTS2018,BraTS2017,Cohort Name (if publicly available),Site No (represents the originating institution),Local ID
84,BraTS-GLI-00120-000,BraTS2021_00120,BraTS20_Training_187,BraTS19_TCIA02_430_1,Brats18_TCIA02_430_1,Brats17_TCIA_430_1,TCGA-GBM,6,TCGA-06-0145
1104,BraTS-GLI-01520-000,BraTS2021_01520,BraTS20_Training_315,BraTS19_TCIA10_632_1,Brats18_TCIA10_632_1,Brats17_TCIA_632_1,TCGA-LGG,13,TCGA-DU-A6S7

In [28]:
mapping_mri = mapping_mri[["Local ID ", "BraTS2023"]]
mapping_mri['MRI'] = mapping_mri['BraTS2023'].apply(lambda x: os.path.join(base_path, 'MRI', x))
mapping_mri.drop(columns=['BraTS2023'], inplace=True)
mapping_mri.rename(columns={'Local ID ': 'submitter_id'}, inplace=True)

In [29]:
mapping_mri.sample(5)

      submitter_id                                       MRI
1071  TCGA-DU-5851  /data/BraTS_2023/MRI/BraTS-GLI-01487-000
96    TCGA-14-1456  /data/BraTS_2023/MRI/BraTS-GLI-00134-000
108   TCGA-02-0009  /data/BraTS_2023/MRI/BraTS-GLI-00149-000
82    TCGA-19-1789  /data/BraTS_2023/MRI/BraTS-GLI-00117-000
1027  TCGA-06-0179  /data/BraTS_2023/MRI/BraTS-GLI-01443-000

In [30]:
dataframe = pd.merge(
    how='left',
    left=dataframe,
    right=mapping_mri, 
    on='submitter_id'
)

In [31]:
dataframe.sample(2)

,submitter_id,tumor_stage,age_at_diagnosis,prior_treatment,prior_malignancy,synchronous_malignancy,days_to_last_follow_up,gender,race,vital_status,...,MGMT,X1p19q,19.20.gain,7g10l,TERT,ATRX,DNAm,RNA,splits,MRI
937,TCGA-HT-7691,NaN,11465.0,No,no,No,3.0,female,white,Alive,...,Unmethylated,non-codel,No chr 19/20 gain,No combined CNA,Not expressed,WT,NaN,../../DRIM/data/TCGA/GBMLGG/RNA/60353a97-9450-...,NaN,NaN
771,TCGA-19-5954,NaN,26355.0,No,NaN,NaN,NaN,female,white,Dead,...,Methylated,non-codel,No chr 19/20 gain,Gain chr 7 & loss chr 10,NaN,WT,NaN,NaN,3.0,/data/BraTS_2023/MRI/BraTS-GLI-00138-000

In [36]:
dataframe.to_csv(dataset_file_path)

In [7]:
len(dataframe[(~dataframe['MRI'].isna()) & (dataframe['group'] == 'train')])

126

In [8]:
len(dataframe[(~dataframe['MRI'].isna()) & (dataframe['group'] == 'test')])

39